// @ts-check
/**
 * AAL ESLint configuration.
 *
 * Two jobs, both of which are quality gates rather than style preferences:
 *
 *   1. Template accessibility (PRD §6.5.1) — every angular-eslint a11y rule at
 *      `error`. These are the Angular equivalent of eslint-plugin-jsx-a11y,
 *      which the research proposal named but which cannot work here: it parses
 *      JSX, so on Angular templates it would silently check nothing. See
 *      PRD §19.1.
 *
 *   2. Layer boundaries (PRD §7.6) — `no-restricted-imports` zones enforcing the
 *      §7.2 dependency graph. Chosen over Nx tags in ADR-0011. An import that
 *      violates the layering fails lint, and lint failure fails CI, so the
 *      architecture stays honest without depending on reviewer discipline.
 */

const eslint = require('@eslint/js');
const tseslint = require('typescript-eslint');
const angular = require('angular-eslint');

/**
 * Layer graph from PRD §7.3. Each entry lists what that layer may NOT import.
 * Imports flow downward only: tokens <- a11y-core <- primitives <- components.
 */
const forbidden = (groups, message) => ({
  'no-restricted-imports': ['error', { patterns: [{ group: groups, message }] }],
});

module.exports = tseslint.config(
  {
    ignores: [
      'dist/**',
      'out-tsc/**',
      'coverage/**',
      'reports/**',
      'node_modules/**',
      '.angular/**',
      'storybook-static/**',
      // Generated by `npm run tokens:build`; regenerating is the way to change it.
      'libs/tokens/src/lib/tokens.generated.ts',
      // Deliberately broken fixtures. Excluded from the normal run; linted
      // programmatically (with `ignore: false`) by tools/lint-gate/lint-gate.spec.mjs,
      // which asserts the expected rules actually fire.
      'tools/lint-gate/fixtures/**',
    ],
  },

  // ----------------------------------------------------------- TypeScript
  {
    files: ['**/*.ts'],
    extends: [
      eslint.configs.recommended,
      ...tseslint.configs.recommended,
      ...tseslint.configs.stylistic,
      ...angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    rules: {
      '@angular-eslint/directive-selector': [
        'error',
        { type: 'attribute', prefix: 'aal', style: 'camelCase' },
      ],
      '@angular-eslint/component-selector': [
        'error',
        { type: 'element', prefix: 'aal', style: 'kebab-case' },
      ],

      // PRD §7.11 rule 5 — signal inputs/outputs, not decorator side effects.
      '@angular-eslint/prefer-signals': 'error',
      '@angular-eslint/prefer-output-emitter-ref': 'warn',

      // OnPush everywhere (PRD §7.7); zoneless compatibility depends on it.
      '@angular-eslint/prefer-on-push-component-change-detection': 'error',

      // Standalone is the only supported shape (FR-01).
      '@angular-eslint/prefer-standalone': 'error',

      // A public API that leaks `any` cannot enforce accessible usage in types.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-definitions': ['error', 'interface'],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],

      // NFR-10 — maintainability budget.
      complexity: ['error', 10],
    },
  },

  // ------------------------------------------------- Templates (a11y gate)
  {
    files: ['**/*.html'],
    extends: [...angular.configs.templateRecommended, ...angular.configs.templateAccessibility],
    rules: {
      // PRD §6.5.1 — all at `error`, no exceptions. Listed explicitly rather
      // than inherited so that a future angular-eslint release cannot silently
      // downgrade one of them to a warning without this file changing.
      '@angular-eslint/template/alt-text': 'error',
      '@angular-eslint/template/elements-content': 'error',
      '@angular-eslint/template/label-has-associated-control': 'error',
      '@angular-eslint/template/valid-aria': 'error',
      '@angular-eslint/template/role-has-required-aria': 'error',
      '@angular-eslint/template/no-positive-tabindex': 'error',
      '@angular-eslint/template/no-autofocus': 'error',
      '@angular-eslint/template/click-events-have-key-events': 'error',
      '@angular-eslint/template/mouse-events-have-key-events': 'error',
      '@angular-eslint/template/interactive-supports-focus': 'error',
      '@angular-eslint/template/table-scope': 'error',
      '@angular-eslint/template/no-distracting-elements': 'error',
      '@angular-eslint/template/button-has-type': 'error',
      '@angular-eslint/template/prefer-control-flow': 'error',

      // Inline styles cannot be overridden by a consumer's theme and escape the
      // token system entirely — which means they escape the contrast gate too.
      '@angular-eslint/template/no-inline-styles': [
        'error',
        { allowNgStyle: true, allowBindToStyle: true },
      ],
    },
  },

  // ------------------------------------------------------ Layer boundaries
  {
    files: ['libs/tokens/**/*.ts'],
    rules: forbidden(
      ['@aal/a11y-core*', '@aal/primitives*', '@aal/components*', '@angular/*'],
      'L1 tokens must contain no Angular code and no AAL imports (PRD §7.3). It has to stay consumable by the contrast validator and the VPAT generator, neither of which runs Angular.',
    ),
  },
  {
    files: ['libs/a11y-core/**/*.ts'],
    rules: forbidden(
      ['@aal/primitives*', '@aal/components*'],
      'L2 a11y-core must not import from L3 primitives or L4 components (PRD §7.3). It renders no DOM and must be unit-testable without a component host.',
    ),
  },
  {
    files: ['libs/primitives/**/*.ts'],
    rules: forbidden(
      ['@aal/components*'],
      'L3 primitives must not import from L4 components (PRD §7.3). Primitives carry behaviour; components carry presentation.',
    ),
  },

  // ------------------------------------------------------------ Test files
  {
    files: ['**/*.spec.ts'],
    rules: {
      // Tests locate elements the way a screen reader does (CLAUDE.md, PRD §11.4).
      // getByTestId is banned: if a test cannot find an element by role and
      // accessible name, neither can assistive technology — and that failure is
      // the accessibility defect, not a testing inconvenience.
      'no-restricted-syntax': [
        'error',
        {
          selector:
            "CallExpression[callee.name=/^(getByTestId|queryByTestId|findByTestId|getAllByTestId|queryAllByTestId|findAllByTestId)$/]",
          message:
            'getByTestId is banned in AAL tests (PRD §11.4). Query by role and accessible name instead — if that is not possible, the component is not accessible and the test has found a real defect.',
        },
        {
          selector: "MemberExpression[property.name='only'][object.name=/^(describe|it|test)$/]",
          message: 'Remove .only before committing — it silently disables the rest of the suite.',
        },
      ],
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  // ----------------------------------------------------------- Build tools
  {
    files: ['tools/**/*.mjs', '*.config.mjs', 'libs/tokens/build-tokens.mjs'],
    languageOptions: {
      globals: { process: 'readonly', console: 'readonly', URL: 'readonly' },
    },
    rules: {
      'no-console': 'off',
      complexity: 'off',
    },
  },
);
